# apply only to this group; empty for all groups (default: all)
group=

# The color options can be one of following:
# 1. Black, Red, Green, Yellow, Blue, Purple, Cyan, White, or Default
# 2. Single index between 0 and 255
# 3. RGB values as #RRGGBB in hex or R,G,B in decimal
# For reference: https://en.wikipedia.org/wiki/ANSI_escape_code#Colors

# The text color for the [therapist] prefix
tag_color=

# The background color for the [therapist] prefix
tag_background=

# The text color for the message content
text_color=

# The background color for the message content
text_background=
